import Head from 'next/head';
import { useContext } from 'react';
import Navbar from '../components/organisms/Navbar';
import { GetIdContext } from '../context/GetId';
import data from '../data';

const Discover = (props) => {
  const { getId, onGetId } = useContext(GetIdContext);

  const contentActive = (id) => {
    onGetId(id);
    console.log(id);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className="bg-smoothblue max-h-screen flex justify-between gap-4 pt-20 sm:px-4 md:px-24">
        <div className="w-2/3 flex justify-center sticky top-0">
          <iframe
            src={`https://www.youtube.com/embed/${getId}`}
            frameBorder="0"
            width={768}
            height={480}
          />
        </div>
        <div className="w-1/3">
          <h2 className="text-center font-semibold text-lg mb-4 border-b border-black">
            Support other creators
          </h2>
          <div className="overflow-y-auto max-h-[80%] flex flex-col gap-2">
            {data.map((item) => (
              <button
                key={item.id}
                className={`w-full text-left hover:border-2 hover:border-teal-300 hover:rounded-xl hover:bg-teal-100 ${
                  item.id === getId ? 'btn-active' : 'border-2 border-transparent'
                } p-4`}
                onClick={() => contentActive(item.id)}
              >
                <h3>{item.title}</h3>
                <p>{item.creator}</p>
              </button>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Discover;
