import jwtDecode from 'jwt-decode';
import Head from 'next/head';
import { useContext } from 'react';
import { useEffect } from 'react';
import Navbar from '../components/organisms/Navbar';
import { getAllContentsAPI } from '../services/contents';
import { ActiveContentCtx } from '../context/getActiveContent';
import { CounterContext } from '../context/counterContext';
import { setCounterSeen, setCounterWatch } from '../services/points';

const Discover = ({ contents, creator }) => {
  const {
    fullname,
    getFullname,
    getIdContent,
    getTitleContent,
    idContent,
    title,
    getUrlContent,
    url,
  } = useContext(ActiveContentCtx);

  const { updaterCounter } = useContext(CounterContext);

  useEffect(() => {
    contents;
  }, [contents]);

  const activeContent = async (id, fullname, title, url, idCreator) => {
    getFullname(fullname);
    getIdContent(id);
    getTitleContent(title);
    getUrlContent(url);

    // counter
    if (creator.status === 'N') {
      return;
    } else if (creator.id_creator !== idCreator) {
      await setCounterWatch(creator.id_creator);
      await setCounterSeen(idCreator);
    }
    updaterCounter(true);
  };

  return (
    <>
      <Head>
        <title>GoShare</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar creator={creator} />
      <main className="bg-smoothblue min-h-screen flex justify-between gap-4 pt-20 pb-6 sm:px-4 md:px-24">
        <div className="w-2/3 flex flex-col sticky top-0">
          <iframe
            src={`https://www.youtube.com/embed/${url}`}
            frameBorder="0"
            width={768}
            height={420}
          />
          <div>
            <h3 className="font-bold italic text-xl mt-2">{title}</h3>
            <p className="font-medium text-base">{fullname}</p>
          </div>
        </div>
        <div className="w-1/3 rounded-md bg-white shadow-xl">
          <div className="p-4 rounded-md bg-goDarkBlue mb-2 shadow-lg">
            <h2 className="text-center font-bold text-lg text-[#FFBE17] italic">
              Support other creators
            </h2>
          </div>
          <div className="flex flex-col gap-1">
            {contents.map((item) => (
              <button
                key={item.id_content}
                className={`w-full text-left hover:border-2 hover:border-teal-300 hover:rounded-xl hover:bg-teal-100 ${
                  item.id_content === idContent ? 'btn-active' : 'border-2 border-transparent'
                } p-4`}
                onClick={() =>
                  activeContent(
                    item.id_content,
                    item.fullname,
                    item.title,
                    item.url,
                    item.id_creator,
                  )
                }
              >
                <h3 className="font-semibold text-md truncate hover:text-clip hover:overflow-auto hover:whitespace-normal">
                  {item.title}
                </h3>
                <p className="font-normal text-md">{item.fullname}</p>
              </button>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export async function getServerSideProps({ req }) {
  const { token } = req.cookies;

  if (!token) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    };
  }

  const jwtToken = Buffer.from(token, 'base64').toString('ascii');
  const payload = jwtDecode(jwtToken);
  const { creator } = payload;

  const allContents = await getAllContentsAPI(jwtToken);

  return {
    props: {
      creator,
      contents: allContents.data.result,
    },
  };
}

export default Discover;
